
name: vint
on:
  push:
  pull_request:

jobs:
  vint:
    name: runner / vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: vint
        uses: reviewdog/action-vint@v1
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          reporter: github-pr-review # Change reporter.


